// <auto-generated />
using System;
using FitTakip.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitTakip.Persistence.Migrations
{
    [DbContext(typeof(FitTakipContext))]
    [Migration("20241224133556_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitTakip.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<DateTime?>("AbonelikSonlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EgitmenId")
                        .HasColumnType("int");

                    b.Property<int?>("IsletmeId")
                        .HasColumnType("int");

                    b.Property<int?>("KalanDersSayisi")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreKarmasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statu")
                        .HasColumnType("int");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("FitTakip.Domain.Entities.Olcum", b =>
                {
                    b.Property<long>("OlcumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OlcumId"));

                    b.Property<int>("Bel")
                        .HasColumnType("int");

                    b.Property<int>("Boy")
                        .HasColumnType("int");

                    b.Property<int>("Gogus")
                        .HasColumnType("int");

                    b.Property<int>("Kalca")
                        .HasColumnType("int");

                    b.Property<decimal>("Kilo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Omuz")
                        .HasColumnType("int");

                    b.Property<int>("SagBacak")
                        .HasColumnType("int");

                    b.Property<int>("SagKol")
                        .HasColumnType("int");

                    b.Property<int>("SolBacak")
                        .HasColumnType("int");

                    b.Property<int>("SolKol")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("OlcumId");

                    b.HasIndex("UyeId");

                    b.ToTable("Olcumler");
                });

            modelBuilder.Entity("FitTakip.Domain.Entities.Randevu", b =>
                {
                    b.Property<long>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RandevuId"));

                    b.Property<string>("Açiklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EgitmenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("UyeId")
                        .HasColumnType("int");

                    b.HasKey("RandevuId");

                    b.HasIndex("EgitmenId");

                    b.HasIndex("UyeId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("FitTakip.Domain.Entities.Olcum", b =>
                {
                    b.HasOne("FitTakip.Domain.Entities.Kullanici", "Uye")
                        .WithMany("UyeOlcumleri")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("FitTakip.Domain.Entities.Randevu", b =>
                {
                    b.HasOne("FitTakip.Domain.Entities.Kullanici", "Egitmen")
                        .WithMany("EgitmenRandevulari")
                        .HasForeignKey("EgitmenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FitTakip.Domain.Entities.Kullanici", "Uye")
                        .WithMany("UyeRandevulari")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Egitmen");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("FitTakip.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("EgitmenRandevulari");

                    b.Navigation("UyeOlcumleri");

                    b.Navigation("UyeRandevulari");
                });
#pragma warning restore 612, 618
        }
    }
}
